### ISSUE TITLE
On Scheduling Entries and Photos

### ISSUE THREAD

**Issue by bshoults** [khalwat/buffer#2]
I have a blog that I'm using your plugin and Buffer to post. The issue is that I'm wanting to schedule out the posts in Craft. Is this possible with `queueBufferUpdate`?

Also, I've not had to develop or mess with any plugins before so am not sure how to pull my blog image into the buffer update. This is my attempt to post my image...I just pulled out the image portion of the code.

`$picture = craft()->request->getUrl($entry->blogImage);`

`craft()->buffer_utils->queueBufferUpdate($updateString, true, $link, $picture, $thumbnail);`

**Comment by khalwat** [comment]
Yeah unfortunately, it doesn't work that way currently. There's no event we can hook into for future publishing that I'm aware of.
